### PR TITLE
Typo error updated for destructiveActionWithTitle

### PR DESCRIPTION
**Pull request by macromania**

### CODE REVIEW

**Comment by BayPhillips** [comment]
Thanks for the PR @macromania ! Could you please also update the corresponding demo as it looks like the renaming wasn't done there. Thanks!

**Comment by macromania** [comment]
Yeah whenever I have time :+1:

**Comment by BayPhillips** [comment]
Hi @macromania, any luck with the renaming in the example? I'd love to merge this guy on in :)

**Comment by macromania** [comment]
Sorry didn't have time for this yet :(

**Comment by BayPhillips** [comment]
We ended up grabbing this in another PR. Thanks though @macromania :+1:

**Pull request closed without merging**
