### PR TITLE
Support for actions to be enabled in iOS8

### PR DESCRIPTION
**Pull request by leolion75**
This is a change to support action to be enabled in iOS8 using NSNotificationCenter.

### CODE REVIEW

**Comment by platedbay** [comment]
Hey @leolion75, thank you for the PR! I apologize that I've been a bit busy but this looks interesting! I'll do my best to taking a look at this ASAP.

**Comment by platedbay** [comment]
I'm so sorry I took so long! This looks great and thank you so much for contributing to this! Merging in now!

**Comment by BayPhillips** [comment]
I'm so sorry this took me so long to get to! Thank you so much for the PR! Things look great! Merging in now :+1:

**Comment by leolion75** [comment]
No problem. thanks for creating the initial project. 

-Leo

**Pull request merged**
